/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import control.CertificadoTableControl;
import control.ClienteControl;
import control.SolicitacaoControl;
import java.io.IOException;
import java.text.ParseException;


/**
 *
 * @author cleolaptop
 */
public class InfoCertificado extends javax.swing.JFrame {
    public int id, id_cli; // id do certificado e do cliente
    public String versao, serial, algoAss, emissor, validoDe, validoAte, nomeComum, organizacao, unOrg, cidade, estado, pais, chavePublica, status;
    /**
     * Creates new form InfoSolicitacao
     * @param id
     * @param versao
     * @param validoAte
     * @param nomeComum
     * @param emissor
     * @param status
     * @throws java.sql.SQLException
     */
    
    /*
    public InfoCertificado(int id, int id_cliente, String versao, String serial, String algoAss, 
            String emissor, String validoDe, String validoAte, String nomeComum, String organizacao, String unOrg,
            String cidade, String estado, String pais, String chavePublica, String status) {
    */
    public InfoCertificado (int id, String versao, String emissor, String validoAte, String nomeComum, String status) throws SQLException {
        this.id = id;
        this.versao = versao;
        this.emissor = emissor;
        this.validoAte = validoAte;
        this.nomeComum = nomeComum;
        this.status = status;
        
        initComponents();
        
        myInitComponents();
    }
    
    private void myInitComponents() throws SQLException {
        String tipo = CertificadoTableControl.analisaSolCert(id);
        
        //System.out.println("tipo="+tipo);
        
        if ("Renovacao".equals(tipo) || "Revogacao".equals(tipo)) {
            jButton_Renovar.setEnabled(false);
            jButton_Revogar.setEnabled(false);
        }
    }
    
    
        /* METODOS ADICIONAIS */
    public void setID (int id) {
        this.id_cert.setText(Integer.toString(id));
    }
    
    public void setID_cliente (int id_cli) {
        this.id_cliente.setText(Integer.toString(id_cli));
    }
    
    public void setVersao (String versao) {
        this.versao_cert.setText(versao);
    }
    
    public void setSerial (String serial) {
        this.serial_cert.setText(serial);
    }    
    
    public void setAlgoAss (String algoAss) {
        this.algoAss_cert.setText(algoAss);
    }
    
    public void setEmissor (String emissor) {
        this.emissor_cert.setText(emissor);
    }
    
    public void setValidoDe (String validoDe) {
        this.validoDE_cert.setText(validoDe);
    }    
    
    public void setValidoAte (String validoAte) {
        this.validoATE_cert.setText(validoAte);
    }    
    
    public void setNomeComum (String nomeComum) {
        this.nomeComum_cert.setText(nomeComum);
    }    
    
    public void setOrganizacao (String organizacao) {
        this.organizacao_cert.setText(organizacao);
    }    
    
    public void setUnOrg (String unOrg) {
        this.unidadeOrg_cert.setText(unOrg);
    }    
    
    public void setCidade (String cidade) {
        this.cidade_cert.setText(cidade);
    }    
    
    public void setEstado (String estado) {
        this.estado_cert.setText(estado);
    }    
    
    public void setPais (String pais) {
        this.pais_cert.setText(pais);
    }    
    
    public void setChavePublica (String chavePublica) {
        this.chavePublica_cert.setText(chavePublica);
    }    
    
    public void setStatus (String status) {
        this.status_cert.setText(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        versao_cert = new javax.swing.JTextField();
        serial_cert = new javax.swing.JTextField();
        algoAss_cert = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emissor_cert = new javax.swing.JTextField();
        validoDE_cert = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        validoATE_cert = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nomeComum_cert = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        organizacao_cert = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        unidadeOrg_cert = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cidade_cert = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        estado_cert = new javax.swing.JTextField();
        pais_cert = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        chavePublica_cert = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        status_cert = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton_Renovar = new javax.swing.JButton();
        jButton_Revogar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        id_cert = new javax.swing.JTextField();
        downloadCert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InfoCertificado");

        jLabel1.setText("ID Cliente");

        jLabel2.setText("Versão:");

        jLabel3.setText("Número de Série:");

        jLabel4.setText("Algoritmo de Assinatura:");

        id_cliente.setEnabled(false);

        versao_cert.setEnabled(false);
        versao_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versao_certActionPerformed(evt);
            }
        });

        serial_cert.setEnabled(false);
        serial_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serial_certActionPerformed(evt);
            }
        });

        algoAss_cert.setEnabled(false);
        algoAss_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoAss_certActionPerformed(evt);
            }
        });

        jLabel7.setText("Emissor:");

        emissor_cert.setEnabled(false);
        emissor_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emissor_certActionPerformed(evt);
            }
        });

        validoDE_cert.setEnabled(false);
        validoDE_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validoDE_certActionPerformed(evt);
            }
        });

        jLabel8.setText("Valido De:");

        jLabel9.setText("Valido Até:");

        validoATE_cert.setEnabled(false);
        validoATE_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validoATE_certActionPerformed(evt);
            }
        });

        jLabel10.setText("Nome Comum:");

        nomeComum_cert.setEnabled(false);
        nomeComum_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeComum_certActionPerformed(evt);
            }
        });

        jLabel11.setText("Organização:");

        organizacao_cert.setEnabled(false);
        organizacao_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizacao_certActionPerformed(evt);
            }
        });

        jLabel12.setText("Unidade de Organização:");

        unidadeOrg_cert.setEnabled(false);
        unidadeOrg_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadeOrg_certActionPerformed(evt);
            }
        });

        jLabel13.setText("Cidade:");

        cidade_cert.setEnabled(false);
        cidade_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_certActionPerformed(evt);
            }
        });

        jLabel14.setText("Estado:");

        estado_cert.setEnabled(false);
        estado_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_certActionPerformed(evt);
            }
        });

        pais_cert.setEnabled(false);
        pais_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pais_certActionPerformed(evt);
            }
        });

        jLabel15.setText("País:");

        chavePublica_cert.setEnabled(false);
        chavePublica_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chavePublica_certActionPerformed(evt);
            }
        });

        jLabel16.setText("Chave Pública:");

        jLabel17.setText("STATUS DO CERTIFICADO:");

        status_cert.setEnabled(false);
        status_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_certActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Informações do seu Certificado:");

        jButton_Renovar.setText("Renovar Certificado");
        jButton_Renovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RenovarActionPerformed(evt);
            }
        });

        jButton_Revogar.setText("Revogar Certificado");
        jButton_Revogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RevogarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Voltar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID Certificado");

        id_cert.setEnabled(false);
        id_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_certActionPerformed(evt);
            }
        });

        downloadCert.setText("Download do certificado");
        downloadCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadCertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(downloadCert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Renovar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Revogar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id_cliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id_cert))
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(versao_cert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial_cert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(validoDE_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(validoATE_cert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(nomeComum_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(organizacao_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(unidadeOrg_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(cidade_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addComponent(estado_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(pais_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(10, 10, 10)
                        .addComponent(chavePublica_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(10, 10, 10)
                        .addComponent(status_cert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(emissor_cert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(algoAss_cert, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(id_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(versao_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serial_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(algoAss_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emissor_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(validoDE_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(validoATE_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nomeComum_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(organizacao_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(unidadeOrg_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cidade_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(estado_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pais_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(chavePublica_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(status_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(downloadCert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Renovar)
                    .addComponent(jButton_Revogar)
                    .addComponent(jButton_Cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new PrincipalCliente().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InfoCertificado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void versao_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versao_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_versao_certActionPerformed

    private void serial_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serial_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serial_certActionPerformed

    private void algoAss_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoAss_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_algoAss_certActionPerformed

    private void emissor_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emissor_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emissor_certActionPerformed

    private void validoDE_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validoDE_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validoDE_certActionPerformed

    private void validoATE_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validoATE_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validoATE_certActionPerformed

    private void nomeComum_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeComum_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeComum_certActionPerformed

    private void organizacao_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizacao_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizacao_certActionPerformed

    private void unidadeOrg_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadeOrg_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadeOrg_certActionPerformed

    private void cidade_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_certActionPerformed

    private void estado_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado_certActionPerformed

    private void pais_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pais_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pais_certActionPerformed

    private void chavePublica_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chavePublica_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chavePublica_certActionPerformed

    private void status_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_certActionPerformed

    private void jButton_RenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RenovarActionPerformed
        try {
            // TODO add your handling code here:
            id_cli = Integer.valueOf(id_cliente.getText());
            serial = serial_cert.getText();
            SolicitacaoControl.enviaSolicitacaoRenovacao(this, id_cli, serial, validoATE_cert.getText());
            //ClienteControl.solicitaRenovacaoCert(id_cli, serial);
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(InfoCertificado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_RenovarActionPerformed

    private void jButton_RevogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RevogarActionPerformed
        try {
            // TODO add your handling code here:
            id_cli = Integer.valueOf(id_cliente.getText());
            serial = serial_cert.getText();
            SolicitacaoControl.enviaSolicitacaoRevogacao(this, id_cli, serial);
            //ClienteControl.solicitaRevogacaoCert();
        } catch (SQLException ex) {
            Logger.getLogger(InfoCertificado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_RevogarActionPerformed

    private void id_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_certActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_certActionPerformed

    private void downloadCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadCertActionPerformed
        try {
            // TODO add your handling code here:
            ClienteControl.downloadCert(serial_cert.getText());
        } catch (IOException ex) {
            Logger.getLogger(InfoCertificado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_downloadCertActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField algoAss_cert;
    private javax.swing.JTextField chavePublica_cert;
    private javax.swing.JTextField cidade_cert;
    private javax.swing.JButton downloadCert;
    private javax.swing.JTextField emissor_cert;
    private javax.swing.JTextField estado_cert;
    private javax.swing.JTextField id_cert;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Renovar;
    private javax.swing.JButton jButton_Revogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeComum_cert;
    private javax.swing.JTextField organizacao_cert;
    private javax.swing.JTextField pais_cert;
    private javax.swing.JTextField serial_cert;
    private javax.swing.JTextField status_cert;
    private javax.swing.JTextField unidadeOrg_cert;
    private javax.swing.JTextField validoATE_cert;
    private javax.swing.JTextField validoDE_cert;
    private javax.swing.JTextField versao_cert;
    // End of variables declaration//GEN-END:variables
}