/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import control.SolicitacaoControl;
import control.SolicitacaoTableControl;

/**
 *
 * @author cleolaptop
 */
public class InfoSolicitacao extends javax.swing.JFrame {
    public int id, id_cli; // id da solicitacao e do cliente
    public String data, tipo, status, serial;
    /**
     * Creates new form Certificado
     * @param id
     * @param id_cli
     * @param data
     * @param tipo
     * @param status
     * @param serial
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public InfoSolicitacao(int id, int id_cli, String data, String tipo, String status, String serial) throws SQLException, IOException {
        this.id = id;
        this.id_cli = id_cli;
        this.data = data;
        this.tipo = tipo;
        this.status = status;
        this.serial = serial;
        
        initComponents();
        
        myInitComponents();
    }
    
    private void myInitComponents() throws SQLException, IOException {
        if ("Aprovada".equals(status) || "Reprovada".equals(status)) {
            jButton_reprovar.setEnabled(false);
            jButton_aprovar.setEnabled(false);
        }
        
        if ("Emissao".equals(tipo))
            SolicitacaoControl.mostraImagem(img, id);
    }
    
    
    
    /* METODOS ADICIONAIS */
    public void setID (int id) {
        this.id_sol.setText(Integer.toString(id));
    }
    
    public void setID_Cliente (int id_cli) {
        this.id_cliente.setText(Integer.toString(id_cli));
    }
    
    public void setData (String data) {
        this.dataSol.setText(data);
    }
    
    public void setTipo (String tipo) {
        this.tipoSol.setText(tipo);
    }
    
    public void setStatus (String status) {
        this.statusSol.setText(status);
    }    
    
    public void setSerial (String serial) {
        this.serialCert.setText(serial);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_info = new javax.swing.JLabel();
        jButton_reprovar = new javax.swing.JButton();
        jButton_aprovar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id_sol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dataSol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoSol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statusSol = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        serialCert = new javax.swing.JTextField();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InfoSolicitacao");

        jLabel_info.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_info.setText("Informações da solicitação:");

        jButton_reprovar.setText("Reprovar");
        jButton_reprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reprovarActionPerformed(evt);
            }
        });

        jButton_aprovar.setText("Aprovar");
        jButton_aprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aprovarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Voltar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Solicitação:");

        id_sol.setEnabled(false);
        id_sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_solActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Cliente:");

        id_cliente.setEnabled(false);
        id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_clienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Data da Solicitação:");

        dataSol.setEnabled(false);
        dataSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSolActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Solicitação:");

        tipoSol.setEnabled(false);
        tipoSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoSolActionPerformed(evt);
            }
        });

        jLabel5.setText("Status da Solicitação:");

        statusSol.setEnabled(false);
        statusSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusSolActionPerformed(evt);
            }
        });

        jLabel6.setText("Comprovante:");

        jLabel7.setText("Serial do Certificado:");

        serialCert.setEnabled(false);
        serialCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialCertActionPerformed(evt);
            }
        });

        img.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(21, 21, 21)
                                .addComponent(serialCert))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(id_sol)
                                    .addComponent(id_cliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusSol, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoSol, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataSol, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_info)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_reprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_aprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_info)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statusSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(serialCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_reprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_aprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new PrincipalTabeliao().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InfoSolicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void id_solActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_solActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_solActionPerformed

    // vai emitir o certificado, e vai dar um insert no banco na tabela Certificado com o id do cliente
    // mudar o status da solicitacao como "Aprovado"
    private void jButton_aprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aprovarActionPerformed
        try {
            SolicitacaoControl.analisaSolicitacao(id, id_cli);
            SolicitacaoTableControl.atualizarSolicitacoes(this, id, "Aprovada");
        } catch (Exception ex) {
            Logger.getLogger(InfoSolicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_aprovarActionPerformed

// mudar o status da solicitacao como "Reprovado"
    private void jButton_reprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reprovarActionPerformed
        try {
            // TODO add your handling code here:
            SolicitacaoTableControl.atualizarSolicitacoes(this, id, "Reprovada");
        } catch (SQLException ex) {
            Logger.getLogger(InfoSolicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_reprovarActionPerformed

    private void id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_clienteActionPerformed

    private void dataSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataSolActionPerformed

    private void tipoSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoSolActionPerformed

    private void statusSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusSolActionPerformed

    private void serialCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialCertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialCertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataSol;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JTextField id_sol;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_aprovar;
    private javax.swing.JButton jButton_reprovar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField serialCert;
    private javax.swing.JTextField statusSol;
    private javax.swing.JTextField tipoSol;
    // End of variables declaration//GEN-END:variables

}
