/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.SolicitacaoControl;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cleolaptop
 */
public class NovaSolicitacao extends javax.swing.JFrame {
    
    String caminhoImg;
    File file = null;

    /**
     * Creates new form Solicitacao
     */
    public NovaSolicitacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Solicitacao = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_EnviarDoc = new javax.swing.JLabel();
        jLabel_RG = new javax.swing.JLabel();
        jLabel_organizacao = new javax.swing.JLabel();
        jLabel_unidadeOrg = new javax.swing.JLabel();
        jButton_Browse = new javax.swing.JButton();
        organizacao = new javax.swing.JTextField();
        unidadeOrg = new javax.swing.JTextField();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_EnviarSolicitacao = new javax.swing.JButton();
        imagemDoc = new javax.swing.JLabel();
        jButton_SalvarImg = new javax.swing.JButton();
        imagemEscolhida = new javax.swing.JTextField();
        jLabel_chaveSecreta = new javax.swing.JLabel();
        jLabel_confirmaChaveSecreta = new javax.swing.JLabel();
        chaveSecreta = new javax.swing.JPasswordField();
        confirmaChaveSecreta = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitacao");

        jPanel_Solicitacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Titulo.setText("Solicitação de Certificado Digital:");

        jLabel_EnviarDoc.setText("Envie a documentação necessária e, em seguida espere aprovação:");

        jLabel_RG.setText("Documento de identificação com foto:");

        jLabel_organizacao.setText("Organização:");

        jLabel_unidadeOrg.setText("Unidade Organizacional:");

        jButton_Browse.setText("Escolher arquivo");
        jButton_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_EnviarSolicitacao.setText("Enviar solicitação");
        jButton_EnviarSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnviarSolicitacaoActionPerformed(evt);
            }
        });

        imagemDoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_SalvarImg.setText("Salvar Imagem");
        jButton_SalvarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarImgActionPerformed(evt);
            }
        });

        jLabel_chaveSecreta.setText("Chave Secreta:");

        jLabel_confirmaChaveSecreta.setText("Confirme a Chave Secreta:");

        javax.swing.GroupLayout jPanel_SolicitacaoLayout = new javax.swing.GroupLayout(jPanel_Solicitacao);
        jPanel_Solicitacao.setLayout(jPanel_SolicitacaoLayout);
        jPanel_SolicitacaoLayout.setHorizontalGroup(
            jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                        .addComponent(jLabel_organizacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(organizacao))
                    .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                        .addComponent(jLabel_unidadeOrg)
                        .addGap(17, 17, 17)
                        .addComponent(unidadeOrg))
                    .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                        .addComponent(imagemDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_SalvarImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imagemEscolhida)))
                    .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                        .addComponent(jLabel_confirmaChaveSecreta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmaChaveSecreta))
                    .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                        .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Titulo)
                            .addComponent(jLabel_EnviarDoc)
                            .addComponent(jLabel_RG)
                            .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                                .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_EnviarSolicitacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                                .addComponent(jLabel_chaveSecreta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chaveSecreta)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_SolicitacaoLayout.setVerticalGroup(
            jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EnviarDoc)
                .addGap(18, 18, 18)
                .addComponent(jLabel_RG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imagemDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_SolicitacaoLayout.createSequentialGroup()
                        .addComponent(jButton_Browse)
                        .addGap(18, 18, 18)
                        .addComponent(imagemEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_SalvarImg)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_organizacao)
                    .addComponent(organizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_unidadeOrg)
                    .addComponent(unidadeOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_chaveSecreta)
                    .addComponent(chaveSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_confirmaChaveSecreta)
                    .addComponent(confirmaChaveSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel_SolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancelar)
                    .addComponent(jButton_EnviarSolicitacao))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Solicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Solicitacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseActionPerformed
        // TODO add your handling code here:
        File fileRet = SolicitacaoControl.escolherImagem(this, file, imagemDoc, imagemEscolhida);
        file = fileRet;
    }//GEN-LAST:event_jButton_BrowseActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new PrincipalCliente().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NovaSolicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_EnviarSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnviarSolicitacaoActionPerformed
        try {
            // TODO add your handling code here:
            SolicitacaoControl.enviaSolicitacaoEmissao(this, organizacao.getText(), unidadeOrg.getText(),
                    "Emissao", caminhoImg, chaveSecreta.getPassword(), confirmaChaveSecreta.getPassword());
        } catch (SQLException ex) {
            Logger.getLogger(NovaSolicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_EnviarSolicitacaoActionPerformed

    private void jButton_SalvarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarImgActionPerformed
        try {
            String pathRet = SolicitacaoControl.salvarImagem(this, file, caminhoImg, imagemEscolhida.getText());
            caminhoImg = pathRet;

        } catch (IOException ex) {
            Logger.getLogger(NovaSolicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_SalvarImgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField chaveSecreta;
    private javax.swing.JPasswordField confirmaChaveSecreta;
    private javax.swing.JLabel imagemDoc;
    private javax.swing.JTextField imagemEscolhida;
    private javax.swing.JButton jButton_Browse;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_EnviarSolicitacao;
    private javax.swing.JButton jButton_SalvarImg;
    private javax.swing.JLabel jLabel_EnviarDoc;
    private javax.swing.JLabel jLabel_RG;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_chaveSecreta;
    private javax.swing.JLabel jLabel_confirmaChaveSecreta;
    private javax.swing.JLabel jLabel_organizacao;
    private javax.swing.JLabel jLabel_unidadeOrg;
    private javax.swing.JPanel jPanel_Solicitacao;
    private javax.swing.JTextField organizacao;
    private javax.swing.JTextField unidadeOrg;
    // End of variables declaration//GEN-END:variables
}
