/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;

import control.CertificadoTableControl;
import control.ClienteControl;
import static control.Main.usuario;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import model.ClienteTableModel;

/**
 *
 * @author cleolaptop
 */
public class PrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalCliente
     * @throws java.sql.SQLException
     */
    public PrincipalCliente() throws SQLException {
        initComponents();
        
        tabelaCert.setModel(new ClienteTableModel());
        tabelaCert.addMouseListener(new CertificadoTableControl(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AcessoCliente = new javax.swing.JPanel();
        jLabel_BemVindo = new javax.swing.JLabel();
        jButton_Solicitar = new javax.swing.JButton();
        jButton_Logout = new javax.swing.JButton();
        jLabel_CertificadosDisponiveis = new javax.swing.JLabel();
        jButton_MostraCRL = new javax.swing.JButton();
        jScrollPane_Certificados = new javax.swing.JScrollPane();
        tabelaCert = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PrincipalCliente");

        jLabel_BemVindo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_BemVindo.setText("Bem vindo");

        jButton_Solicitar.setText("Solicitar Certificado");
        jButton_Solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SolicitarActionPerformed(evt);
            }
        });

        jButton_Logout.setText("Logout");
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });

        jLabel_CertificadosDisponiveis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_CertificadosDisponiveis.setText("Certificados disponíveis:");

        jButton_MostraCRL.setText("Lista de Certificados Revogados");
        jButton_MostraCRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MostraCRLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_AcessoClienteLayout = new javax.swing.GroupLayout(jPanel_AcessoCliente);
        jPanel_AcessoCliente.setLayout(jPanel_AcessoClienteLayout);
        jPanel_AcessoClienteLayout.setHorizontalGroup(
            jPanel_AcessoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AcessoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AcessoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AcessoClienteLayout.createSequentialGroup()
                        .addComponent(jLabel_BemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Logout))
                    .addGroup(jPanel_AcessoClienteLayout.createSequentialGroup()
                        .addGroup(jPanel_AcessoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_CertificadosDisponiveis)
                            .addComponent(jButton_MostraCRL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Solicitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_AcessoClienteLayout.setVerticalGroup(
            jPanel_AcessoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AcessoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AcessoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BemVindo)
                    .addComponent(jButton_Logout))
                .addGap(5, 5, 5)
                .addComponent(jButton_Solicitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_MostraCRL)
                .addGap(19, 19, 19)
                .addComponent(jLabel_CertificadosDisponiveis)
                .addContainerGap())
        );

        tabelaCert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaCert.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Certificados.setViewportView(tabelaCert);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_AcessoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jScrollPane_Certificados, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_AcessoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_Certificados, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SolicitarActionPerformed
        // TODO add your handling code here:
        //SolicitacaoControl.solicitaEmissaoBOTAO(this);
        ClienteControl.solicitarBotao(this);
        
    }//GEN-LAST:event_jButton_SolicitarActionPerformed

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        // TODO add your handling code here:        
        ClienteControl.logoutBotao(this);
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    private void jButton_MostraCRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MostraCRLActionPerformed
        try {
            // TODO add your handling code here:
            ClienteControl.mostraCertificadosRevogados();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(PrincipalCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_MostraCRLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_MostraCRL;
    private javax.swing.JButton jButton_Solicitar;
    private javax.swing.JLabel jLabel_BemVindo;
    private javax.swing.JLabel jLabel_CertificadosDisponiveis;
    private javax.swing.JPanel jPanel_AcessoCliente;
    private javax.swing.JScrollPane jScrollPane_Certificados;
    private javax.swing.JTable tabelaCert;
    // End of variables declaration//GEN-END:variables
}